/*!
 * \file      demoRanging.c
 *
 * \brief     Ranging demo implementation.
 *
 * \copyright Revised BSD License, see section \ref LICENSE.
 *
 * \code
 *                ______                              _
 *               / _____)             _              | |
 *              ( (____  _____ ____ _| |_ _____  ____| |__
 *               \____ \| ___ |    (_   _) ___ |/ ___)  _ \
 *               _____) ) ____| | | || |_| ____( (___| | | |
 *              (______/|_____)_|_|_| \__)_____)\____)_| |_|
 *              (C)2013-2017 Semtech
 *
 * \endcode
 *
 * \Maintainer: Miguel Luis, Matthieu Verdy and Benjamin Boulet
 */


/* Includes ------------------------------------------------------------------*/

#include "hw.h"
#include "radio.h"
#include "sx1280.h"
#include "utilities.h"
#include "demoRanging.h"
#include "shared_spi_bus.h"
#include "board_ui.h"
#include "spi_mutex.h"
#include "sx1280_hal_hc32.h"
#include "timer_hc32.h"
#if( DEMO_FREQ_HOPPED_RANGING == 1 )
#include "FreqLUT.h"
#endif


/****************************************************************************\
 * CONSTANT and MACRO definition
\****************************************************************************/

/*!
 * \brief Size of ticks (used for Tx and Rx timeout)
 */
#define RX_TIMEOUT_TICK_SIZE            RADIO_TICK_SIZE_1000_US

/*!
 * \brief Ranging Timer value
 */
#define RNG_TIMER_MS                    384 // ms
#define RNG_COM_TIMEOUT                 100 // ms

/* 中值为负时的板级路径补偿 (m)，仅用于距离显示 */
#define DEMO_RNG_RESULT_OFFSET_M        3.2

/* 主机测距 DIO1：必须含 RESULT_TIMEOUT(0x0400)，不能用 IrqRangingCode_t 的 ERROR_CODE(=2) */
#define MASTER_RANGING_IRQ_MASK         ( IRQ_RX_DONE | IRQ_TX_DONE | IRQ_RX_TX_TIMEOUT | \
                                          IRQ_RANGING_MASTER_RESULT_VALID | \
                                          IRQ_RANGING_MASTER_RESULT_TIMEOUT )
/* 测距进行中仅保留 ranging 中断，避免 RX_DONE 误触发 APP_RX 回到握手 */
#define MASTER_RANGING_RUN_IRQ_MASK     ( IRQ_RANGING_MASTER_RESULT_VALID | \
                                          IRQ_RANGING_MASTER_RESULT_TIMEOUT )

/* 允许超时重试；factor×RngRequestCount 为单轮最大 hop 次数（30×20=600） */
#define RNG_MAX_ATTEMPTS_FACTOR           20u
/* 方案 A：Semtech 公式 delay 乘数（SF7+BW800 约 24 ms ×2 = 48 ms） */
#define RNG_REQ_DELAY_FACTOR              2u

/* 从机：主机停发后连续无成功跳数达阈值 → 立即回到监听 */
#define SLAVE_SESSION_IDLE_KO_THRESHOLD       16u
#define SLAVE_SESSION_IDLE_KO_THRESHOLD_CONT  8u
#define MASTER_HANDSHAKE_MAX_ATTEMPTS         8u
#define MASTER_SLAVE_RESYNC_DELAY_MS          1200u

/*!
 * \brief Defines the local payload buffer size
 */
#define BUFFER_SIZE                     16
#define DEMO_UART_BUFFER_SIZE           255


#if( DEMO_FREQ_HOPPED_RANGING == 1 )

/*!
 * \brief Size of channels array
 */
#define CHANNELS 40
/*
 * Frequency look up table :
 * To avoid Wifi channels, 40 Bluetooth channels are defined below (they already
 * avoid Wifi common channels) : from 2402 MHz to 2480 MHz, step 2 MHz.
 * User can define channel count for Ranging run, and it is optimized to have
 * several frequencies in the largest band as possible. Also the 40 frequencies
 * are generated by random sorting to preferate the 10 first in the largest band
 * as possible (10 is the shortest channel count the user can choose).
 */
const uint32_t rangingChannels[] =
{
 2450000000,
 2402000000,
 2476000000,
 2436000000,
 2430000000,
 2468000000,
 2458000000,
 2416000000,
 2424000000,
 2478000000,
 2456000000,
 2448000000,
 2462000000,
 2472000000,
 2432000000,
 2446000000,
 2422000000,
 2442000000,
 2460000000,
 2474000000,
 2414000000,
 2464000000,
 2454000000,
 2444000000,
 2404000000,
 2434000000,
 2410000000,
 2408000000,
 2440000000,
 2452000000,
 2480000000,
 2426000000,
 2428000000,
 2466000000,
 2418000000,
 2412000000,
 2406000000,
 2470000000,
 2438000000,
 2420000000,
};
#else //( DEMO_FREQ_HOPPED_RANGING == 0 )

/*!
 * \brief Single channel Configuration
 */
#define CHANNELS 1

const uint32_t rangingChannels[] = { 2450000000 };

#endif //( DEMO_FREQ_HOPPED_RANGING == 1 )

/*!
 * \brief Ranging raw factors
 *                                  SF5     SF6     SF7     SF8     SF9     SF10
 */
const uint16_t RNG_CALIB_0400[] = { 10299,  10271,  10244,  10242,  10230,  10246  };
const uint16_t RNG_CALIB_0800[] = { 11486,  11474,  11453,  11426,  11417,  11401  };
const uint16_t RNG_CALIB_1600[] = { 13308,  13493,  13528,  13515,  13430,  13376  };
const double   RNG_FGRAD_0400[] = { -0.148, -0.214, -0.419, -0.853, -1.686, -3.423 };
const double   RNG_FGRAD_0800[] = { -0.041, -0.811, -0.218, -0.429, -0.853, -1.737 };
const double   RNG_FGRAD_1600[] = { 0.103,  -0.041, -0.101, -0.211, -0.424, -0.87  };

/***************************************************************************\
 * External function Prototype
\***************************************************************************/

/*!
 * \brief Function to be executed on Radio Tx Done event
 */
void OnTxDone( void );

/*!
 * \brief Function to be executed on Radio Rx Done event
 */
void OnRxDone( void );

/*!
 * \brief Function executed on Radio Tx Timeout event
 */
void OnTxTimeout( void );

/*!
 * \brief Function executed on Radio Rx Timeout event
 */
void OnRxTimeout( void );

/*!
 * \brief Function executed on Radio Rx Error event
 */
void OnRxError( IrqErrorCode_t );

/*!
 * \brief Function executed on Radio Rx Error event
 */
void OnRangingDone( IrqRangingCode_t );

/*!
 * \brief Switch Antenna during ranging demo
 */
void SetAntennaSwitch( void );

/***************************************************************************\
 * RAM data
\***************************************************************************/

/*!
 * \brief Main demo settings.
 */
DemoSettings_t DemoSettings;

/*!
 * \brief Ranging demo results.
 */
DemoResult_t DemoResults;

/*!
 * \brief Locals parameters and status
 */
static bool demoReady = false;
static RangingDemoStatus_t demoStatus;
static ModulationParams_t modulationParams;
static PacketParams_t packetParams;

/*!
 * \brief Flag to indicate if the demo is already running
 */
static bool demoRunning = false;

/*!
 * \brief Flag holding the current internal state of the demo application
 */
static uint8_t demoInternalState;

/*!
 * \brief Channels information variables
 */
static uint8_t currentChannel;
static uint16_t measuredChannels;

/*!
 * \brief Buffer and its size
 */
static uint8_t demoBufferSize = BUFFER_SIZE;
static uint8_t demoBuffer[BUFFER_SIZE];


static uint8_t SendNext = false;

static uint32_t s_slaveLastRxOkCount = 0u;
static uint16_t s_hopsSinceLastSuccess = 0u;
static uint8_t  s_rngSessionId = 0u;
static uint8_t  s_operatingMode = RNG_OP_MODE_DEMO;
static void ( *s_idleHook )( void ) = NULL;
static uint8_t  s_quickSessionStarted = 0u;
static uint8_t  s_masterHandshakeFails = 0u;

/*!
 * \brief All the callbacks are stored in a structure
 */
RadioCallbacks_t Callbacks =
{
    &OnTxDone,        // txDone
    &OnRxDone,        // rxDone
    NULL,             // syncWordDone
    NULL,             // headerDone
    &OnTxTimeout,     // txTimeout
    &OnRxTimeout,     // rxTimeout
    &OnRxError,       // rxError
    &OnRangingDone,   // rangingDone
    NULL,             // cadDone
};

/***************************************************************************\
 * Local function Prototype
\***************************************************************************/

/*!
 * \brief Get the distance from the raw ranging results.
 *
 * \retval cntPacketRxOKSlave   The number of packet received.
 */
uint8_t RangingDemoCheckDistance( void );

/*!
 * \brief Check if the radio can send the next ranging packet.
 *
 * \retval sendNext   [True : Send next packet, False: Wait ]
 */
bool RangingDemoCheckTimer( void );

/*!
 * \brief Initialize the demo parameters.
 *
 * \param [in] modulation   Indicates the modulation to initialize
 */
void RangingDemoInitializeParameters( uint8_t modulation );

static void RangingDemoSessionCleanup( void );
static void RangingDemoSlaveRestartSession( void );
static uint16_t RangingDemoGetHopBudget( void );
static uint8_t RangingDemoGetHopFactor( void );
static uint16_t RangingDemoGetMinValidSamples( void );
static void RangingDemoTerminateSession( void );
static void RangingDemoMasterHandshakeFailed( void );
static uint16_t RangingDemoGetSlaveIdleThreshold( void );
static uint8_t RangingDemoSlaveTryHandshake( void );
static void RangingDemoDelayMs( uint32_t delayMs );

/*!
 * \brief Callback of ticker PerSendNextPacket
 */
void SendNextPacketEvent( void );
/***************************************************************************\
 *  APPLICATION INTERFACES functions definition
\***************************************************************************/

/*!
 * \brief Initialize the ranging demo.
 *
 * \param [in] demoEntity    The demo entity (either MASTER or SLAVE)
 */
void RangingDemoInitApplication( uint8_t demoEntity )
{

    // Initialize and select the radio.
    Radio.Init( &Callbacks );

    // Set the settings to default values.
    DemoSettings.Entity         = demoEntity;
    DemoSettings.RadioPowerMode = USE_DCDC;
    DemoSettings.Frequency      = DEMO_CENTRAL_FREQ_PRESET2;
    DemoSettings.TxPower        = DEMO_POWER_TX_MAX;

    DemoSettings.ModulationType = PACKET_TYPE_RANGING;
    modulationParams.PacketType = PACKET_TYPE_RANGING;
    packetParams.PacketType     = PACKET_TYPE_RANGING;

    packetParams.Params.LoRa.PreambleLength = 12u;
    packetParams.Params.LoRa.HeaderType     = LORA_PACKET_VARIABLE_LENGTH;
    packetParams.Params.LoRa.CrcMode        = LORA_CRC_ON;
    packetParams.Params.LoRa.InvertIQ       = LORA_IQ_NORMAL;

    modulationParams.Params.LoRa.SpreadingFactor = LORA_SF7;
    modulationParams.Params.LoRa.Bandwidth       = LORA_BW_0800;
    modulationParams.Params.LoRa.CodingRate      = LORA_CR_4_5;

    DemoSettings.RngRequestCount = 30u;
    DemoSettings.RngFullScale    = 30u;
    DemoSettings.RngAddress      = DEMO_RNG_ADDR_1;
    DemoSettings.RngAntenna      = DEMO_RNG_ANT_1;
    DemoSettings.RngUnit         = DEMO_RNG_UNIT_SEL_M;

    memset( &demoBuffer, 0x00u, demoBufferSize );

    // Set the results to default values.
    DemoResults.CntPacketTx    = 0u;
    DemoResults.CntPacketRxOK  = 0u;
    DemoResults.CntPacketRxKO  = 0u;
    DemoResults.RxTimeOutCount = 0u;

    // Set the local demo status.
    demoReady                  = true;
    demoRunning                = false;
    demoInternalState          = APP_IDLE;
    SendNext                   = false;

}

/*!
 * \brief Set the ranging demo settings.
 *
 * \param [in] nbRequest     The radio to select
 * \param [in] address       The ranging Address
 * \param [in] antenna       The selected antenna
 * \param [in] unitSelect    The selected unit (m, yd or mi)
 */
void RangingDemoSetRangingParameters( uint8_t nbRequest, uint32_t address, uint8_t antenna, uint8_t unitSelect )
{

    DemoSettings.RngRequestCount = nbRequest;
    DemoSettings.RngAddress      = address;
    DemoSettings.RngAntenna      = antenna;
    DemoSettings.RngUnit         = unitSelect;

}

/*!
 * \brief Set the ranging radio settings.
 *
 * \param [in] spreadingFactor  The spreading factor value
 * \param [in] bandwidth        The bandwidth value
 * \param [in] codingRate       The coding Rate value
 * \param [in] frequency        The frequency value
 * \param [in] txPower          The TX power value
 */
void RangingDemoSetRadioParameters( RadioLoRaSpreadingFactors_t spreadingFactor, RadioLoRaBandwidths_t bandwidth, RadioLoRaCodingRates_t codingRate, uint32_t frequency, int8_t txPower )
{

    modulationParams.Params.LoRa.SpreadingFactor = spreadingFactor;
    modulationParams.Params.LoRa.Bandwidth       = bandwidth;
    modulationParams.Params.LoRa.CodingRate      = codingRate;
	DemoSettings.SpreadingFactor                 = spreadingFactor;
    DemoSettings.Bandwidth                       = bandwidth;
    DemoSettings.Frequency                       = frequency;
    DemoSettings.TxPower                         = txPower;
}

/*!
 * \brief Run the ranging demo.
 *
 * \retval demoStatus  Indicates the status of the demo.
 */
RangingDemoStatus_t RangingDemoRun( void )
{

    // Check the demo has been initialized.
    if( demoReady == false )
    {
        return DEMO_RANGING_NOT_CONFIGURED;   // quit without refresh display
    }

    if( ( DemoSettings.Entity == MASTER ) &&
        ( s_operatingMode != RNG_OP_MODE_CONTINUOUS ) &&
        ( BoardUiIsRangingArmed() == 0u ) )
    {
        return DEMO_RANGING_NOT_CONFIGURED;
    }

    demoStatus = DEMO_RANGING_RUNNING;

    if( demoRunning == false )
    {
        // Initialize local demo parameters.
        demoRunning = true;

        DemoResults.CntPacketTx = 0u;
        DemoResults.RngFei      = 0.0;
        DemoResults.RngResultIndex = 0;
        DemoSettings.RngStatus   = RNG_INIT;
        RangingDemoInitializeParameters( DemoSettings.ModulationType );

        if( DemoSettings.Entity == SLAVE )
        {
            s_slaveLastRxOkCount = 0u;
        }

        if( DemoSettings.Entity == MASTER )
        {
            Radio.SetDioIrqParams( MASTER_RANGING_IRQ_MASK,
                                   MASTER_RANGING_IRQ_MASK,
                                   IRQ_RADIO_NONE, IRQ_RADIO_NONE);
            if( s_operatingMode != RNG_OP_MODE_CONTINUOUS )
            {
                DemoResults.RngDistance = 0.0;
            }
            demoInternalState = APP_RANGING_CONFIG;
        }
        else
        {
            Radio.SetDioIrqParams( IRQ_RADIO_ALL, IRQ_RADIO_ALL, IRQ_RADIO_NONE, IRQ_RADIO_NONE);
            demoInternalState = APP_RANGING_CONFIG;
        }
    }

    SX1280ProcessIrqs();

    // MASTER Ranging demo
    if( DemoSettings.Entity == MASTER )
    {
        switch( demoInternalState )
        {
            case APP_RANGING_CONFIG:
                if( demoReady == true )
                {
                    DemoSettings.RngStatus = RNG_INIT;
                    DemoResults.CntPacketTx++;
                    modulationParams.PacketType = PACKET_TYPE_LORA;
                    packetParams.PacketType     = PACKET_TYPE_LORA;

                    packetParams.Params.LoRa.PayloadLength = 8u;

                    Radio.SetPacketType( modulationParams.PacketType );
                    Radio.SetModulationParams( &modulationParams );
                    Radio.SetPacketParams( &packetParams );
                    Radio.SetRfFrequency( DemoSettings.Frequency );
                    DemoResults.CntPacketRxOK = 0;
                    DemoResults.CntPacketRxOKSlave = 0;
                    measuredChannels  = 0u;
                    currentChannel    = 0u;
                    demoBuffer[0] = ( DemoSettings.RngAddress >> 24u ) & 0xFFu;
                    demoBuffer[1] = ( DemoSettings.RngAddress >> 16u ) & 0xFFu;
                    demoBuffer[2] = ( DemoSettings.RngAddress >>  8u ) & 0xFFu;
                    demoBuffer[3] = ( DemoSettings.RngAddress & 0xFFu );
                    demoBuffer[4] = currentChannel;    // set the first channel to use
                    demoBuffer[5] = DemoSettings.RngAntenna;      // set the antenna strategy
                    demoBuffer[6] = DemoSettings.RngRequestCount; // set the number of hops
                    demoBuffer[7] = s_rngSessionId;
                    Radio.SetDioIrqParams( MASTER_RANGING_IRQ_MASK,
                                           MASTER_RANGING_IRQ_MASK,
                                           IRQ_RADIO_NONE, IRQ_RADIO_NONE );
                    Radio.SendPayload( demoBuffer, packetParams.Params.LoRa.PayloadLength, ( TickTime_t ){ RX_TIMEOUT_TICK_SIZE, RNG_COM_TIMEOUT });
                    demoInternalState = APP_IDLE;
                }
                break;

            case APP_RNG:
                if( SendNext == true )
                {
                    SendNext = false;
                    measuredChannels++;
                    if( measuredChannels <= RangingDemoGetHopBudget( ) )
                    {
                        Radio.SetRfFrequency( rangingChannels[currentChannel] );
						
						switch( DemoSettings.RngAntenna )
                        {
                            case DEMO_RNG_ANT_1:
								DemoSettings.AntennaSwitch = 1;
								currentChannel++;
                                if( currentChannel >= CHANNELS )
                                {
                                    currentChannel -= CHANNELS;
                                }
							break;
								
							case DEMO_RNG_ANT_2:
								DemoSettings.AntennaSwitch = 2;
                                currentChannel++;
                                if( currentChannel >= CHANNELS )
                                {
                                    currentChannel -= CHANNELS;
                                }
							break;

                            case DEMO_RNG_ANT_BOTH:
                                if( DemoSettings.AntennaSwitch == 1 )
                                {
                                    DemoSettings.AntennaSwitch = 2;
                                }
                                else
                                {
                                    DemoSettings.AntennaSwitch = 2;
                                    currentChannel++;
                                    if( currentChannel >= CHANNELS )
                                    {
                                        currentChannel -= CHANNELS;
                                    }
                                }
							break;
                        }
                        SetAntennaSwitch( );
                        demoInternalState = APP_IDLE;
                        Radio.SetTx( ( TickTime_t ){ RADIO_TICK_SIZE_1000_US, 0xFFFF });
                    }
                    else
                    {
                        RangingDemoTerminateSession( );
                    }
                }
                break;

            case APP_RANGING_DONE:
            {
                PacketStatus_t PacketStatus;

                Radio.GetPacketStatus( &PacketStatus );
                if( DemoResults.RngResultIndex < DemoSettings.RngRequestCount )
                {
                    DemoResults.RawRngRssi[DemoResults.RngResultIndex] = PacketStatus.Params.LoRa.RssiPkt;
                    DemoResults.RawRngResults[DemoResults.RngResultIndex] = Radio.GetRangingResult( RANGING_RESULT_RAW );
                    DemoResults.RawRngResults[DemoResults.RngResultIndex] += SX1280GetRangingCorrectionPerSfBwGain(
                        modulationParams.Params.LoRa.SpreadingFactor,
                        modulationParams.Params.LoRa.Bandwidth,
                        Radio.GetRangingPowerDeltaThresholdIndicator( )
                    );
                    DemoResults.RngResultIndex++;
                    DemoResults.CntPacketRxOK++;
                }

                if( ( s_operatingMode == RNG_OP_MODE_CONTINUOUS ) &&
                    ( DemoResults.RngResultIndex >= DemoSettings.RngRequestCount ) )
                {
                    RangingDemoTerminateSession( );
                    break;
                }

                demoInternalState = APP_RNG;
                TimerCreateTimer( &SendNextPacketEvent, 0, DemoSettings.RngReqDelay );
            }
            break;

            case APP_RANGING_TIMEOUT:
                demoInternalState = APP_RNG;
                TimerCreateTimer( &SendNextPacketEvent, 0, DemoSettings.RngReqDelay );
                break;

            case APP_RX:
                if( DemoSettings.RngStatus == RNG_INIT )
                {
                    Radio.GetPayload( demoBuffer, &demoBufferSize, BUFFER_SIZE );
                    if( demoBufferSize > 0 )
                    {
                        PacketStatus_t PacketStatus;
                        DemoResults.RxTimeOutCount = 0;
                        DemoSettings.RngStatus = RNG_PROCESS;
                        DemoResults.RngFei = ( double )( ( ( int32_t )demoBuffer[4] << 24 ) | \
                                                                            ( ( int32_t )demoBuffer[5] << 16 ) | \
                                                                            ( ( int32_t )demoBuffer[6] <<  8 ) | \
                                                                                         demoBuffer[7] );
                        DemoResults.RssiValue = demoBuffer[8]; // for ranging post-traitment (since V3 only)
                        modulationParams.PacketType = PACKET_TYPE_RANGING;
                        packetParams.PacketType     = PACKET_TYPE_RANGING;

                        packetParams.Params.LoRa.PayloadLength = 10;

                        Radio.GetPacketStatus( &PacketStatus );
                        Radio.SetPacketType( modulationParams.PacketType );
                        Radio.SetModulationParams( &modulationParams );
                        Radio.SetPacketParams( &packetParams );
                        Radio.SetRangingRequestAddress( DemoSettings.RngAddress );
                    Radio.SetRangingCalibration( DemoSettings.RngCalib );
                    Radio.SetTxParams( DemoSettings.TxPower, RADIO_RAMP_20_US );

                    DemoResults.SnrValue = PacketStatus.Params.LoRa.SnrPkt;
                    measuredChannels = 0;
                        DemoResults.RngResultIndex      = 0;
                        DemoResults.CntPacketRxOK       = 0;
                        DemoResults.CntPacketRxOKSlave  = 0;
                        DemoResults.CntPacketRxKOSlave  = 0;
                        s_masterHandshakeFails          = 0u;
                        Radio.RangingClearFilterResult( );
                    demoInternalState = APP_RNG;

                    Radio.SetDioIrqParams( MASTER_RANGING_RUN_IRQ_MASK,
                                           MASTER_RANGING_RUN_IRQ_MASK,
                                           IRQ_RADIO_NONE, IRQ_RADIO_NONE );
                    TimerCreateTimer( &SendNextPacketEvent,0, DemoSettings.RngReqDelay );
                    }
                    else
                    {
                        RangingDemoMasterHandshakeFailed( );
                    }
                }
                else if( DemoSettings.RngStatus == RNG_PROCESS )
                {
                    /* 测距阶段偶发 RX_DONE：忽略，勿回 APP_RANGING_CONFIG 否则 CntPacketTx 暴增 */
                    demoInternalState = APP_IDLE;
                }
                else
                {
                    RangingDemoMasterHandshakeFailed( );
                }
                break;

            case APP_TX:
                if( DemoSettings.RngStatus == RNG_INIT )
                {
                    Radio.SetRx( ( TickTime_t ) { RX_TIMEOUT_TICK_SIZE, RNG_COM_TIMEOUT });
                    demoInternalState = APP_IDLE;
                }
                else if( DemoSettings.RngStatus == RNG_PROCESS )
                {
                    /* 测距阶段忽略 TX_DONE，避免误回 APP_RANGING_CONFIG 打断测距循环 */
                    demoInternalState = APP_IDLE;
                }
                else
                {
                    RangingDemoMasterHandshakeFailed( );
                }
                break;

            case APP_RX_TIMEOUT:
                if( DemoSettings.RngStatus == RNG_PROCESS )
                {
                    demoInternalState = APP_RANGING_TIMEOUT;
                }
                else
                {
                    RangingDemoMasterHandshakeFailed( );
                }
                break;

            case APP_RX_ERROR:
                if( DemoSettings.RngStatus == RNG_PROCESS )
                {
                    demoInternalState = APP_IDLE;
                }
                else
                {
                    RangingDemoMasterHandshakeFailed( );
                }
                break;

            case APP_TX_TIMEOUT:
                if( DemoSettings.RngStatus == RNG_PROCESS )
                {
                    demoInternalState = APP_RANGING_TIMEOUT;
                }
                else
                {
                    RangingDemoMasterHandshakeFailed( );
                }
                break;

            case APP_IDLE:
                if( (DemoSettings.RngStatus == RNG_PROCESS) && (SendNext == true) )
                {
                    demoInternalState = APP_RNG;
                }
                else if( ( DemoSettings.RngStatus == RNG_PROCESS ) &&
                          ( DemoResults.RngResultIndex == 0u ) &&
                          ( DemoResults.CntPacketRxKOSlave > ( (uint32_t)DemoSettings.RngRequestCount * 4u ) ) )
                {
                    RangingDemoSessionCleanup( );
                    demoStatus = DEMO_RANGING_TERMINATED;
                    demoRunning = false;
                    DemoSettings.RngStatus = RNG_PER_ERROR;
                    demoInternalState = APP_RANGING_CONFIG;
                }
                break;

            default:
                demoInternalState = APP_RANGING_CONFIG;
                break;
        }
    }
    else    // Slave Ranging Demo
    {
        switch( demoInternalState )
        {
            case APP_RANGING_CONFIG:
                DemoSettings.RngStatus = RNG_INIT;
                RangingDemoSessionCleanup( );
                measuredChannels                = 0u;
                currentChannel                  = 0u;
                s_hopsSinceLastSuccess          = 0u;
                DemoResults.CntPacketRxOK       = 0u;
                DemoResults.CntPacketRxKOSlave  = 0u;
                modulationParams.PacketType = PACKET_TYPE_LORA;
                packetParams.PacketType     = PACKET_TYPE_LORA;
                packetParams.Params.LoRa.PayloadLength  = 9;

                Radio.SetPacketType( modulationParams.PacketType );
                Radio.SetModulationParams( &modulationParams );
                Radio.SetPacketParams( &packetParams );
                Radio.SetRfFrequency( DemoSettings.Frequency );
                // use listen mode here instead of rx continuous
                Radio.SetRx( ( TickTime_t ) { RADIO_TICK_SIZE_1000_US, 0x1000 } ); //0xFFFF
                demoInternalState = APP_IDLE;
                break;

            case APP_RNG:
                if( SendNext == true )
                {
                    SendNext = false;
                    measuredChannels++;
                    if( measuredChannels <= RangingDemoGetHopBudget( ) )
                    {
						Radio.SetRfFrequency( rangingChannels[currentChannel] );
						switch( DemoSettings.RngAntenna )
                        {
                            case DEMO_RNG_ANT_1:
								DemoSettings.AntennaSwitch = 1;
								currentChannel++;
                                if( currentChannel >= CHANNELS )
                                {
                                    currentChannel -= CHANNELS;
                                }
							break;
								
							case DEMO_RNG_ANT_2:
								DemoSettings.AntennaSwitch = 2;
                                currentChannel++;
                                if( currentChannel >= CHANNELS )
                                {
                                    currentChannel -= CHANNELS;
                                }
							break;

                            case DEMO_RNG_ANT_BOTH:
                                if( DemoSettings.AntennaSwitch == 1 )
                                {
                                    DemoSettings.AntennaSwitch = 2;
                                }
                                else
                                {
                                    DemoSettings.AntennaSwitch = 2;
                                    currentChannel++;
                                    if( currentChannel >= CHANNELS )
                                    {
                                        currentChannel -= CHANNELS;
                                    }
                                }
							break;
                        }
                        SetAntennaSwitch( );
                        demoInternalState = APP_IDLE;
                        Radio.SetRx( ( TickTime_t ){ RADIO_TICK_SIZE_1000_US, DemoSettings.RngReqDelay } );
                    }
                    else
                    {
                        RangingDemoSessionCleanup( );
                        demoStatus = DEMO_RANGING_TERMINATED;
                        demoRunning = false;
                        DemoSettings.RngStatus = RNG_INIT;
                        measuredChannels = 0u;
                        demoInternalState = APP_RANGING_CONFIG;
                    }
                }
                break;

            case APP_RANGING_DONE:
                DemoResults.CntPacketRxOK++;
                s_slaveLastRxOkCount = DemoResults.CntPacketRxOK;
                s_hopsSinceLastSuccess = 0u;
                demoInternalState = APP_RNG;
                TimerCreateTimer( &SendNextPacketEvent, 0, DemoSettings.RngReqDelay );
                break;

            case APP_RANGING_TIMEOUT:
                demoInternalState = APP_RNG;
                TimerCreateTimer( &SendNextPacketEvent, 0, DemoSettings.RngReqDelay );
                break;

            case APP_RX:
                if( RangingDemoSlaveTryHandshake( ) != 0u )
                {
                    break;
                }

                if( DemoSettings.RngStatus == RNG_PROCESS )
                {
                    demoInternalState = APP_RANGING_TIMEOUT;
                }
                else
                {
                    demoInternalState = APP_RANGING_CONFIG;
                }
                break;

            case APP_TX:
                if( DemoSettings.RngStatus == RNG_INIT )
                {
                    DemoSettings.RngStatus = RNG_PROCESS;

                    modulationParams.PacketType = PACKET_TYPE_RANGING;
                    packetParams.PacketType     = PACKET_TYPE_RANGING;

                    packetParams.Params.LoRa.PayloadLength  = 10;

                    Radio.SetPacketType( modulationParams.PacketType );

                    Radio.SetModulationParams( &modulationParams );
                    Radio.SetPacketParams( &packetParams );
                    Radio.SetDeviceRangingAddress( DemoSettings.RngAddress );
                    Radio.SetRangingCalibration( DemoSettings.RngCalib );
                    Radio.SetTxParams( DemoSettings.TxPower, RADIO_RAMP_20_US );
                    Radio.RangingClearFilterResult( );
                    DemoResults.CntPacketRxOK = 0;
                    measuredChannels = 0;
                    DemoResults.CntPacketRxKOSlave = 0;
                    s_hopsSinceLastSuccess = 0u;
                    TimerCreateTimer( &SendNextPacketEvent, 0, DemoSettings.RngReqDelay );
                    demoInternalState = APP_RNG;
                }
                else if( DemoSettings.RngStatus == RNG_PROCESS )
                {
                    demoInternalState = APP_RANGING_TIMEOUT;
                }
                else
                {
                    demoInternalState = APP_RANGING_CONFIG;
                }
                break;

            case APP_RX_TIMEOUT:
                if( DemoSettings.RngStatus == RNG_PROCESS )
                {
                    demoInternalState = APP_RANGING_TIMEOUT;
                }
                else
                {
                    demoInternalState = APP_RANGING_CONFIG;
                }
                break;

            case APP_RX_ERROR:
                if( DemoSettings.RngStatus == RNG_PROCESS )
                {
                    demoInternalState = APP_RANGING_TIMEOUT;
                }
                else
                {
                    demoInternalState = APP_RANGING_CONFIG;
                }
                break;

            case APP_TX_TIMEOUT:
                if( DemoSettings.RngStatus == RNG_PROCESS )
                {
                    demoInternalState = APP_RANGING_TIMEOUT;
                }
                else
                {
                    demoInternalState = APP_RANGING_CONFIG;
                }
                break;

            case APP_IDLE:
                if( ( DemoSettings.RngStatus == RNG_PROCESS ) &&
                    ( s_hopsSinceLastSuccess >= RangingDemoGetSlaveIdleThreshold( ) ) )
                {
                    RangingDemoSlaveRestartSession();
                }
                break;

            default:
                if( DemoSettings.RngStatus == RNG_PROCESS )
                {
                    demoInternalState = APP_RANGING_TIMEOUT;
                }
                else
                {
                    demoInternalState = APP_RANGING_CONFIG;
                    TimerCancelTimer( );
                }
                break;
        }
    }

    if( ( DemoSettings.Entity == MASTER ) && ( DemoResults.RngResultIndex > 0u ) &&
        ( DemoSettings.RngStatus != RNG_PROCESS ) )
    {
        RangingDemoGetResult();
    }

    SX1280ProcessIrqs();

    return demoStatus;
}

void RangingDemoPollRadio( void )
{
    SX1280ProcessIrqs();
}

uint8_t RangingDemoDisplayUpdateAllowed( void )
{
    if( DemoSettings.Entity != MASTER )
    {
        return 0u;
    }
    if( demoStatus == DEMO_RANGING_TERMINATED )
    {
        return 1u;
    }
    if( DemoSettings.RngStatus == RNG_PROCESS )
    {
        return 0u;
    }
    if( BUSY_IS_HIGH() )
    {
        return 0u;
    }
    return 1u;
}

DemoResult_t* RangingDemoGetResultForDisplay( void )
{
    return &DemoResults;
}

uint8_t RangingDemoHasLiveSamples( void )
{
    return ( DemoResults.RngResultIndex > 0u ) ? 1u : 0u;
}

uint8_t RangingDemoGetInternalState( void )
{
    return demoInternalState;
}

uint8_t RangingDemoIsContinuousMode( void )
{
    return ( s_operatingMode == RNG_OP_MODE_CONTINUOUS ) ? 1u : 0u;
}

/*!
 * \brief Reset the ranging demo.
 */
void RangingDemoReset( void )
{
    double savedDistance = 0.0;

    if( s_operatingMode == RNG_OP_MODE_CONTINUOUS )
    {
        savedDistance = DemoResults.RngDistance;
    }

    RangingDemoSessionCleanup( );
    if( s_operatingMode == RNG_OP_MODE_CONTINUOUS )
    {
        if( s_quickSessionStarted != 0u )
        {
            RangingDemoDelayMs( RNG_CONTINUOUS_SESSION_GAP_MS );
        }
    }
    else
    {
        RangingDemoDelayMs( MASTER_SLAVE_RESYNC_DELAY_MS );
    }
    s_rngSessionId++;
    SendNext                        = false;
    demoInternalState               = APP_IDLE;
    demoStatus                      = DEMO_RANGING_NOT_CONFIGURED;
    DemoSettings.RngStatus          = RNG_INIT;
    DemoResults.CntPacketRxKOSlave  = 0u;
    DemoResults.CntPacketRxOK       = 0u;
    DemoResults.CntPacketRxOKSlave  = 0u;
    DemoResults.CntPacketTx         = 0u;
    DemoResults.RngDistance         = savedDistance;
    DemoResults.RngFei              = 0u;
    DemoResults.RssiValue           = 0u;
    DemoResults.RxTimeOutCount      = 0u;
    DemoResults.RngResultIndex      = 0;
    demoRunning                     = false;
    measuredChannels                = 0u;
    currentChannel                  = 0u;
    s_hopsSinceLastSuccess          = 0u;
    s_masterHandshakeFails          = 0u;
}

void RangingDemoSetIdleHook( void ( *hook )( void ) )
{
    s_idleHook = hook;
}

static void RangingDemoDelayMs( uint32_t delayMs )
{
    uint32_t start;
    uint32_t now;

    start = TimerGetTickMs();
    do
    {
        if( s_idleHook != NULL )
        {
            s_idleHook();
        }
        now = TimerGetTickMs();
    } while( ( now - start ) < delayMs );
}

void RangingDemoSetContinuousMode( uint8_t enable )
{
    if( enable != 0u )
    {
        s_operatingMode = RNG_OP_MODE_CONTINUOUS;
        BoardUiArmRanging( );
    }
    else
    {
        s_operatingMode = RNG_OP_MODE_DEMO;
        BoardUiDisarmRanging( );
    }
    s_quickSessionStarted = 0u;
}

void RangingDemoStartQuickSession( void )
{
    RangingDemoReset( );
    s_quickSessionStarted = 1u;
}

/*!
 * \brief Get the ranging demo settings.
 *
 * \retval DemoSettings   Pointer on the settings.
 */
DemoSettings_t* RangingDemoGetConfiguration( void )
{
    return &DemoSettings;
}

/*!
 * \brief Compute the result distance and get the ranging demo results.
 *
 * \retval DemoResults   Pointer on the results.
 */
DemoResult_t* RangingDemoGetResult( void )
{
    DemoResults.CntPacketRxOKSlave = RangingDemoCheckDistance();
    return &DemoResults;
}

/***************************************************************************\
 * Local Function Definition
\***************************************************************************/

static void RangingDemoSessionCleanup( void )
{
    TimerCancelTimer( );
    Radio.SetStandby( STDBY_RC );
}

static uint8_t RangingDemoGetHopFactor( void )
{
    if( s_operatingMode == RNG_OP_MODE_CONTINUOUS )
    {
        return RNG_CONTINUOUS_HOP_FACTOR;
    }
    return RNG_MAX_ATTEMPTS_FACTOR;
}

static uint16_t RangingDemoGetHopBudget( void )
{
    return ( uint16_t )DemoSettings.RngRequestCount * ( uint16_t )RangingDemoGetHopFactor( );
}

static uint16_t RangingDemoGetMinValidSamples( void )
{
    if( DemoSettings.RngRequestCount >= DEMO_RNG_CHANNELS_COUNT_MIN )
    {
        return DEMO_RNG_CHANNELS_COUNT_MIN;
    }
    if( DemoSettings.RngRequestCount <= 1u )
    {
        return 1u;
    }
    return ( ( uint16_t )DemoSettings.RngRequestCount + 1u ) / 2u;
}

static void RangingDemoTerminateSession( void )
{
    RangingDemoSessionCleanup( );
    demoStatus = DEMO_RANGING_TERMINATED;
    demoRunning = false;
    demoInternalState = APP_RANGING_CONFIG;
}

static void RangingDemoMasterHandshakeFailed( void )
{
    s_masterHandshakeFails++;

    if( s_masterHandshakeFails >= MASTER_HANDSHAKE_MAX_ATTEMPTS )
    {
        DemoSettings.RngStatus = RNG_TIMEOUT;
        RangingDemoTerminateSession( );
    }
    else
    {
        DemoSettings.RngStatus = RNG_TIMEOUT;
        demoInternalState = APP_RANGING_CONFIG;
    }
}

static uint16_t RangingDemoGetSlaveIdleThreshold( void )
{
    if( s_operatingMode == RNG_OP_MODE_CONTINUOUS )
    {
        return SLAVE_SESSION_IDLE_KO_THRESHOLD_CONT;
    }

    return SLAVE_SESSION_IDLE_KO_THRESHOLD;
}

static uint8_t RangingDemoSlaveTryHandshake( void )
{
    PacketStatus_t PacketStatus;

    Radio.GetPayload( demoBuffer, &demoBufferSize, BUFFER_SIZE );
    Radio.GetPacketStatus( &PacketStatus );

    if( ( demoBufferSize < 8u ) ||
        ( demoBuffer[0] != ( ( DemoSettings.RngAddress >> 24 ) & 0xFF ) ) ||
        ( demoBuffer[1] != ( ( DemoSettings.RngAddress >> 16 ) & 0xFF ) ) ||
        ( demoBuffer[2] != ( ( DemoSettings.RngAddress >>  8 ) & 0xFF ) ) ||
        ( demoBuffer[3] != (   DemoSettings.RngAddress         & 0xFF ) ) )
    {
        return 0u;
    }

    if( ( DemoSettings.RngStatus == RNG_PROCESS ) &&
        ( demoBuffer[7] == s_rngSessionId ) )
    {
        return 0u;
    }

    RangingDemoSessionCleanup( );
    TimerCancelTimer( );
    measuredChannels                = 0u;
    DemoResults.RngResultIndex      = 0u;
    DemoResults.CntPacketRxKOSlave  = 0u;
    DemoResults.CntPacketRxOK       = 0u;
    s_slaveLastRxOkCount            = 0u;
    s_hopsSinceLastSuccess          = 0u;
    s_rngSessionId                  = demoBuffer[7];
    DemoSettings.RngStatus          = RNG_INIT;
    DemoResults.RngFei              = Radio.GetFrequencyError( );
    DemoResults.RssiValue           = PacketStatus.Params.LoRa.RssiPkt;
    DemoResults.CntPacketTx++;
    currentChannel                  = demoBuffer[4];
    DemoSettings.RngAntenna         = demoBuffer[5];
    DemoSettings.RngRequestCount    = demoBuffer[6];
    modulationParams.PacketType     = PACKET_TYPE_LORA;
    packetParams.PacketType         = PACKET_TYPE_LORA;
    packetParams.Params.LoRa.PayloadLength = 9u;
    Radio.SetPacketType( modulationParams.PacketType );
    Radio.SetModulationParams( &modulationParams );
    Radio.SetPacketParams( &packetParams );
    Radio.SetRfFrequency( DemoSettings.Frequency );
    demoBuffer[4] = ( ( ( int32_t )DemoResults.RngFei ) >> 24 ) & 0xFF;
    demoBuffer[5] = ( ( ( int32_t )DemoResults.RngFei ) >> 16 ) & 0xFF;
    demoBuffer[6] = ( ( ( int32_t )DemoResults.RngFei ) >>  8 ) & 0xFF;
    demoBuffer[7] = ( ( ( int32_t )DemoResults.RngFei ) & 0xFF );
    demoBuffer[8] = DemoResults.RssiValue;
    Radio.SendPayload( demoBuffer, 9, ( TickTime_t ){ RADIO_TICK_SIZE_1000_US, RNG_COM_TIMEOUT } );
    demoInternalState = APP_IDLE;
    return 1u;
}

static void RangingDemoSlaveRestartSession( void )
{
    RangingDemoSessionCleanup( );
    SendNext                        = false;
    measuredChannels                = 0u;
    currentChannel                  = 0u;
    s_slaveLastRxOkCount            = 0u;
    s_hopsSinceLastSuccess          = 0u;

    DemoSettings.RngStatus          = RNG_INIT;
    DemoResults.CntPacketRxKOSlave  = 0u;
    DemoResults.CntPacketRxOK       = 0u;
    DemoResults.CntPacketTx         = 0u;
    DemoResults.RngResultIndex      = 0u;
    DemoResults.RngDistance         = 0u;
    demoInternalState               = APP_RANGING_CONFIG;
}

/*!
 * \brief Callback of ticker PerSendNextPacket
 */
void SendNextPacketEvent( void)
{
    SendNext = true;
    if( ( DemoSettings.Entity == SLAVE ) && ( DemoSettings.RngStatus == RNG_PROCESS ) )
    {
        s_hopsSinceLastSuccess++;
        DemoResults.CntPacketRxKOSlave++;
    }
    else if( ( DemoSettings.Entity == MASTER ) && ( DemoSettings.RngStatus == RNG_PROCESS ) )
    {
        DemoResults.CntPacketRxKOSlave++;
    }

}

/*!
 * \brief Initialize the demo parameters.
 *
 * \param [in] modulation   Indicates the modulation to initialize
 */
void RangingDemoInitializeParameters( uint8_t modulation )
{

    Radio.SetStandby( STDBY_RC );

    Radio.SetRegulatorMode( ( RadioRegulatorModes_t )DemoSettings.RadioPowerMode );

    if( modulation == PACKET_TYPE_LORA )
    {

        modulationParams.PacketType = PACKET_TYPE_LORA;
        packetParams.PacketType     = PACKET_TYPE_LORA;

        packetParams.Params.LoRa.PayloadLength = 10u; // PayloadLength

        Radio.WriteRegister( REG_LNA_REGIME, SX1280HalReadRegister( REG_LNA_REGIME ) | MASK_LNA_REGIME );
    }

    if( modulation == PACKET_TYPE_RANGING )
    {
        Radio.SetBufferBaseAddresses( 0x00u, 0x00u );
        Radio.SetTxParams( DemoSettings.TxPower, RADIO_RAMP_20_US );

        switch( modulationParams.Params.LoRa.Bandwidth )
        {
            case LORA_BW_0400:
                DemoSettings.RngCalib     = RNG_CALIB_0400[ ( modulationParams.Params.LoRa.SpreadingFactor >> 4u ) - 5u ];
                DemoSettings.RngFeiFactor = ( double )RNG_FGRAD_0400[ ( modulationParams.Params.LoRa.SpreadingFactor >> 4u ) - 5u ];
                DemoSettings.RngReqDelay  = RNG_TIMER_MS >> ( 0u + 10u - ( modulationParams.Params.LoRa.SpreadingFactor >> 4u ) );
                break;

            case LORA_BW_0800:
                if( modulationParams.Params.LoRa.SpreadingFactor == LORA_SF7 )
                {
                    DemoSettings.RngCalib = BOARD_RNG_CALIB_SF7_BW800;
                }
                else
                {
                    DemoSettings.RngCalib = RNG_CALIB_0800[ ( modulationParams.Params.LoRa.SpreadingFactor >> 4u ) - 5u ];
                }
                DemoSettings.RngFeiFactor = ( double )RNG_FGRAD_0800[ ( modulationParams.Params.LoRa.SpreadingFactor >> 4u ) - 5u ];
                DemoSettings.RngReqDelay  = RNG_TIMER_MS >> ( 1u + 10u - ( modulationParams.Params.LoRa.SpreadingFactor >> 4u ) );
                break;

            case LORA_BW_1600:
                DemoSettings.RngCalib     = RNG_CALIB_1600[ ( modulationParams.Params.LoRa.SpreadingFactor >> 4u ) - 5u ];
                DemoSettings.RngFeiFactor = ( double )RNG_FGRAD_1600[ ( modulationParams.Params.LoRa.SpreadingFactor >> 4u ) - 5u ];
                DemoSettings.RngReqDelay  = RNG_TIMER_MS >> ( 2u + 10u - ( modulationParams.Params.LoRa.SpreadingFactor >> 4u ) );
                break;
            default:
                break;
        }

        DemoSettings.RngReqDelay *= RNG_REQ_DELAY_FACTOR;

        Radio.SetPollingMode(  );
        Radio.WriteRegister( REG_LNA_REGIME, SX1280HalReadRegister( REG_LNA_REGIME ) & ~MASK_LNA_REGIME );
    }
}

/*!
 * \brief Convert FEI-corrected raw sample to meters.
 */
static double RangingDemoCorrectedRawToMeters( double correctedRaw )
{
    double value = correctedRaw;

    if( value < 0.0 )
    {
        value += DEMO_RNG_RESULT_OFFSET_M;
    }

    if( value < 100.0 )
    {
        return SX1280ComputeRangingCorrectionPolynome(
            modulationParams.Params.LoRa.SpreadingFactor,
            modulationParams.Params.LoRa.Bandwidth,
            value
        );
    }

    return value;
}

/*!
 * \brief Get the distance from the raw ranging results.
 *
 * \retval cntPacketRxOKSlave   The number of packet received.
 */
uint8_t RangingDemoCheckDistance( void )
{
    double displayRange = 0.0;
    double rssi = DemoResults.RssiValue;

    uint16_t j = 0u;
    uint16_t i;

    if( DemoResults.RngResultIndex > 0 )
    {
        for( i = 0; i < DemoResults.RngResultIndex; ++i )
        {
            DemoResults.RngResults[i] = DemoResults.RawRngResults[i]
                - ( DemoSettings.RngFeiFactor * DemoResults.RngFei / 1000.0 );
        }

        for (int i = DemoResults.RngResultIndex - 1; i > 0; --i)
        {
            for (int k = 0; k < i; ++k)
            {
                if (DemoResults.RngResults[k] > DemoResults.RngResults[k + 1])
                {
                    double temp = DemoResults.RngResults[k];
                    DemoResults.RngResults[k] = DemoResults.RngResults[k + 1];
                    DemoResults.RngResults[k + 1] = temp;
                }
            }
        }
        double median;
        if ((DemoResults.RngResultIndex % 2) == 0)
        {
            median = (DemoResults.RngResults[DemoResults.RngResultIndex/2] + DemoResults.RngResults[(DemoResults.RngResultIndex/2) - 1])/2.0;
        }
        else
        {
            median = DemoResults.RngResults[DemoResults.RngResultIndex/2];
        }

        displayRange = RangingDemoCorrectedRawToMeters( median );

        j = DemoResults.RngResultIndex;

        if( demoStatus == DEMO_RANGING_TERMINATED )
        {
            if( j < RangingDemoGetMinValidSamples( ) )
            {
                DemoSettings.RngStatus = RNG_PER_ERROR;
            }
            else
            {
                DemoSettings.RngStatus = RNG_VALID;
            }
        }

        if( displayRange < 0.0 )
        {
            DemoResults.RngDistance = 0.0;
        }
        else
        {
            switch( DemoSettings.RngUnit )
            {
                case DEMO_RNG_UNIT_SEL_M:
                    DemoResults.RngDistance = displayRange;
                    break;

                case DEMO_RNG_UNIT_SEL_YD:
                    DemoResults.RngDistance = displayRange * DEMO_RNG_UNIT_CONV_YD;
                    break;

                case DEMO_RNG_UNIT_SEL_MI:
                    DemoResults.RngDistance = displayRange * DEMO_RNG_UNIT_CONV_MI;
                    break;
            }
        }
    }

    return j;
}

void SetAntennaSwitch( void )
{
#if !defined(BOARD_SINGLE_ONBOARD_ANTENNA) || (BOARD_SINGLE_ONBOARD_ANTENNA == 0)
    if( DemoSettings.AntennaSwitch == 0 )
    {
        SetAntenna1(); // ANT1
    }
    else
    {
        SetAntenna2(); // ANT0
    }
#endif
}

// ************************     Radio Callbacks     ****************************
// *                                                                           *
// * These functions are called through function pointer by the Radio low      *
// * level drivers                                                             *
// *                                                                           *
// *****************************************************************************
void OnTxDone( void )
{
    if( DemoSettings.RngStatus == RNG_PROCESS )
    {
        return;
    }
    demoInternalState = APP_TX;
}

void OnRxDone( void )
{
    if( ( DemoSettings.Entity == MASTER ) && ( DemoSettings.RngStatus == RNG_PROCESS ) )
    {
        return;
    }
    demoInternalState = APP_RX;
}

void OnTxTimeout( void )
{
    if( DemoSettings.RngStatus == RNG_PROCESS )
    {
        demoInternalState = APP_RANGING_TIMEOUT;
        return;
    }
    demoInternalState = APP_TX_TIMEOUT;
}

void OnRxTimeout( void )
{
    if( DemoSettings.RngStatus == RNG_PROCESS )
    {
        demoInternalState = APP_RANGING_TIMEOUT;
        return;
    }
    demoInternalState = APP_RX_TIMEOUT;
}

void OnRxError( IrqErrorCode_t errorCode )
{
    if( DemoSettings.RngStatus == RNG_PROCESS )
    {
        if( DemoSettings.Entity == MASTER )
        {
            return;
        }
        demoInternalState = APP_RANGING_TIMEOUT;
        return;
    }
    demoInternalState = APP_RX_ERROR;
}

void OnRangingDone( IrqRangingCode_t val )
{
    if( val == IRQ_RANGING_MASTER_VALID_CODE || val == IRQ_RANGING_SLAVE_VALID_CODE )
    {
        demoInternalState = APP_RANGING_DONE;
    }
    else if( val == IRQ_RANGING_MASTER_ERROR_CODE || val == IRQ_RANGING_SLAVE_ERROR_CODE )
    {
        demoInternalState = APP_RANGING_TIMEOUT;
    }
    else
    {
        demoInternalState = APP_RANGING_TIMEOUT;
    }
}

void OnCadDone( bool channelActivityDetected )
{
}

